---
## Nexus 2 install

##

  - name: Copy nexus2.yaml to master
    copy:
      src: files/nexus2.yaml
      dest: /root/nexus2.yaml

  - name: Check if Nexus was already provisioned
    command: "oc get service nexus -n opentlc-shared"
    register: install_nexus
    ignore_errors: true

  - name: Instantiate nexus from template
    command: "oc create -f /root/nexus2.yaml -n opentlc-shared"
    when: install_nexus | failed

  # looks like we need a better check - it seems we're ready up to several
  # seconds before the router finds out about us, so we might want another
  # http check to make sure nexus is responding
  - name: Wait for Nexus to be running
    command: "oc get dc/nexus -o yaml -n opentlc-shared"
    register: result
    until: '"availableReplicas: 1" in result.stdout'
    retries: 5
    delay: 60

  - name: Install EPEL (for jq)
    package:
      name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      state: installed

  - name: Disable EPEL
    command: "yum-config-manager --disablerepo=epel"

  - name: Install jq
    package:
      name: jq
      state: present
      enablerepo: epel

  - name: Copy Nexus addrepo script
    copy:
      src: files/addrepo.sh
      dest: /root/addrepo.sh

  - name: Check for redhat-ga repository in Nexus
    uri:
      url: "http://nexus.opentlc-shared.svc.cluster.local:8081/content/repositories/redhat-ga"
      status_code: 200
    register: redhat_ga_out
    ignore_errors: true

  - name: Add redhat-ga repository for Nexus
    shell: "NEXUS_BASE_URL=nexus.opentlc-shared.svc.cluster.local:8081 bash /root/addrepo.sh redhat-ga https://maven.repository.redhat.com/ga/"
    when: redhat_ga_out | failed

  - name: Check for JBoss repository in Nexus
    uri:
      url: "http://nexus.opentlc-shared.svc.cluster.local:8081/content/repositories/jboss"
      status_code: 200
    register: jboss_out
    ignore_errors: true

  - name: Add jboss repository for Nexus
    shell: "NEXUS_BASE_URL=nexus.opentlc-shared.svc.cluster.local:8081 bash /root/addrepo.sh jboss https://repository.jboss.org/nexus/content/repositories/public"
    when: jboss_out | failed
