
#########################Configuring openshfit-provisioner

- name: Configuring openshfit-provisioner
  hosts: bastions
  become: yes
  vars_files:
    - "../configs/standard_configs/{{ config_name }}/{{ config_name }}_vars.yml"
  roles:
    - openshift-provisioner
  tags: [ openshift_provisioner_tasks ]


#########################Configuring openshfit-nodes

- name: Configuring openshfit-nodes
  hosts: infranodes,nodes
  become: yes
  vars_files:
    - "../configs/standard_configs/{{ config_name }}/{{ config_name }}_vars.yml"
  roles:
    - openshift-node
  tags: [ openshift_node_tasks ]


######################### Run OpenShift Installer


- name: Run OpenShift Installer
  hosts: bastions
  become: yes
  vars_files:
    - "../configs/standard_configs/{{ config_name }}/{{ config_name }}_vars.yml"
  tags: [ installing_openshift ]
  tasks:

    - name: Add log path to Ansible configuration
      lineinfile:
        regexp: "^#log_path"
        dest: "/etc/ansible/ansible.cfg"
        line: "log_path = /root/ansible.log"
        state: present

    - name: run ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
      shell: "ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
      register: openshift_install_log
      tags: [ openshfit_installer ]

    - name: get openshfit credentials file
      shell: ansible masters[0] -b -m fetch -a "src=/root/.kube/config dest=/root/.kube/config flat=yes"
      tags: [ get_openshift_credentials ]
