# ## Logon credentials for Red Hat Network
# ## Required if using the subscription component
# ## of this playbook.
# rhel_subscription_user: ''
# rhel_subscription_pass: ''
#
# ## LDAP Bind Password
# bindPassword: ''
#
# ## Desired openshift admin name and password
# admin_user: ""
# admin_user_password: ""
#
# ## AWS Credentials. This is required.
# aws_access_key_id: ""
# aws_secret_access_key: ""
